---
# tasks file for build_server
- name: Install the packages build server
  apt: name={{item}} state=present
  with_items:
    - default-jdk
    - maven
    - git
- git:
    clone: yes
    repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
    dest: /opt/
- name: Build Maven artifact
  command: mvn -f /opt/pom.xml package